name: Movie/api
on:
  push:
    branches:
      - develop
  workflow_dispatch: null
concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true
env:
  MONGO_DATABASE: '${{ secrets.MONGO_DATABASE }}'
  MONGO_USER: '${{ secrets.MONGO_USER }}'
  MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'
  MONGO_CLUSTER: '${{ secrets.MONGO_CLUSTER }}'
  GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
  GCP_ZONE: '${{ secrets.GCP_ZONE }}'
  GKE_CLUSTER: '${{ secrets.GKE_CLUSTER }}'
  GKE_CREDENTIALS: '${{ secrets.GKE_CREDENTIALS }}'
  SERVICE_ACCOUNT: '${{ secrets.SERVICE_ACCOUNT }}'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 20
          lfs: true
      - run: >-
          docker build
          --build-arg MONGO_DATABASE=$MONGO_DATABASE
          --build-arg MONGO_USER=$MONGO_USER
          --build-arg MONGO_CLUSTER=$MONGO_CLUSTER
          --build-arg MONGO_PASSWORD=$MONGO_PASSWORD
          -t gcr.io/ise-test-404109/movie-prod-api:latest .
      - run: 'docker push gcr.io/wilduche/movie-api:latest'
